### PR TITLE
Fix hybrid compilation: private/internal variables should be uniquely renamed before changing visibility

### LINKED ISSUE #8: Hybrid command fails at link
CERE hybrid command can fail at binary link. When multiple regions are extracted into separated files, many global variables are set to public visibility (since they must be visible from the extracted region) and can induce name conflict at link.

### PR DESCRIPTION
**Pull request by Chadi-akel**
When extracting multiple regions from different files (for per region
compilation) internal global variables are changed to public visibility
wich causes conflicts at link. This patch renames internal global variables
(before any extraction) with a unique name to avoid names conflict.

Fixes #8

### CODE REVIEW

**Comment by pablooliveira** [comment]
It would be great if you could finish #10 before merging this !

**Comment by pablooliveira** [comment]
In line https://github.com/benchmark-subsetting/cere/commit/90f54536b89c32ff5d8cf117030acf8f2c89e91f#diff-f8a5c712cdb5bd34b2807eb8cb332204R53 you use `M.getModuleIdentifier()` which returns the name of the module. What happens if you rename multiple variables on the same module; how do you handle the collision ?

This seems either a bug, or something that should be clarified with a comment in the code.

**Comment by pablooliveira** [comment]
Currently we change the visibility of internal variables used by extracted code with a `sed` hack in lec. I think it would be nice to make the visibility change directly in this pass.

**Comment by Chadi-akel** [comment]
@pablooliveira: Thank you for your comments
- #10 is merged.
- I commented the fact that setName handles names collisions.
- For the visibility hack with `sed`, you're right it can be done in this pass but global renaming is done before any extraction and the visibility update is done after last optimization step. So we have to call this pass twice. I am opening a ticket for this.

**Comment by pablooliveira** [comment]
Thanks for the clarification about collisions !

Your point about `sed` also makes sense. We can leave that for later.

But, please do not merge until #14 is fully fixed. I think it's important that our tests pass cleanly on travis before adding new stuff.

**Comment by pablooliveira** [comment]
All tests are passing. Merging !

@Chadi-akel: You wrote
"For the visibility hack with sed, you're right it can be done in this pass but global renaming is done before any extraction and the visibility update is done after last optimization step. So we have to call this pass twice. I am opening a ticket for this." 

Could you please open the enhancement ticket just to remember to merge all the visibility changes in this pass at some point ?

Thanks !

**Pull request merged**
