### PR TITLE
Fix Travis script

### PR DESCRIPTION
**Pull request by Chadi-akel**
Added a package for documentation compilation.
Fix tests that are failing.

Change-Id: Ib187bdf5213121b66f5703e0b213335bc789f2a4

### CODE REVIEW

**Comment by pablooliveira** [comment]
"Added a package for documentation compilation."

If you say that you fix the documentation, you should add "ruby-rdiscount" to INSTALL.md.

**Comment by Chadi-akel** [comment]
Actually I am still trying to fix it and it doesn't work yet even with the "ruby-rdiscount" package. When I'll find the good setup I'll update necessary files.

**Comment by Chadi-akel** [comment]
Ok finally on travis trusty version I had some problems with installations of python and ruby. Compilations problems disappeared on the default ubuntu version. I've also updated installation file.

**Comment by pablooliveira** [comment]
Great work Chadi ! I added a small patch to fix the rdiscount dependency and merged your work in #18. Closing.

**Comment by Chadi-akel** [comment]
Ok thank you Pablo for your help.

**Pull request merged**
