### PR TITLE
Support openmp with llvm 7

### PR DESCRIPTION
**Pull request by mihailpopov**
Provide support of openmp with LLVM 7.

### CODE REVIEW

**Comment by mihailpopov** [comment]
I do not easily understand why this build fails.

The *make check* command is used in both *Run CERE tests* and *Build & install CERE*.
Yet, *make check* only fails in *Run CERE tests*.

Something must be different between the two. 
Is it possible that a cached version is used: i previously forgot to push the makefiles in the tests, so maybe the checker is reusing a previous cached version? 
If it is not obvious, I can spend more time on this later.

**Comment by mihailpopov** [comment]
Hum, actually by looking at the log file:
```
./test_Omp_Blackscholes
not ok 10 ./test_Omp_Blackscholes
FAIL: testplan.test 10 ./test_Omp_Blackscholes
INFO 10/03/2022 15:25:01 CERE : Start
INFO 10/03/2022 15:25:01 Configure : Configuration success
INFO 10/03/2022 15:25:01 CERE : Stop
INFO 10/03/2022 15:25:02 CERE : Start
INFO 10/03/2022 15:25:02 Capture : Compiling capture mode for region __cere__blackscholes_m4__Z9bs_threadPv_368 invocation 10
INFO 10/03/2022 15:25:02 Capture : Capturing invocation 10 for region __cere__blackscholes_m4__Z9bs_threadPv_368
ERROR 10/03/2022 15:25:02 Capture : Command './blackscholes 4 in_64K.txt out' returned non-zero exit status 127
ERROR 10/03/2022 15:25:02 Capture : ./blackscholes: error while loading shared libraries: libomp.so: cannot open shared object file: No such file or directory
```

It seems that the system has issues finding libomp.so.
Is it possible that we need to export the same variables in  "Run CERE tests" as they are in "Build & install CERE"?

```
      - name: Build & install CERE
        run: |
          export PATH=/opt/llvm-7/bin:$PATH \n\
          export LD_LIBRARY_PATH=/opt/llvm-7/libexec:/opt/llvm-7/lib:$LD_LIBRARY_PATH
          export LIBRARY_PATH=/opt/llvm-7/libexec:/opt/llvm-7/lib:$LIBRARY_PAT
          export C_INCLUDE_PATH=/opt/llvm-7/include:$C_INCLUDE_PATH
          export CPLUS_INCLUDE_PATH=/opt/llvm-7/include:$CPLUS_INCLUDE_PATH
          # NOTE To generate doc wit ronn, we need to set locale to UTF-8 English
          apt-get -y install locales
          locale-gen --no-purge en_US.UTF-8
          export LANG="en_US.UTF-8"
          export LANGUAGE="en_US:en"
          export LC_ALL="en_US.UTF-8"   
          #We are building cere with clang because with the LLVM 7 binary release, llvm-config would throw flags not recognized by GCC
          libtoolize && ./autogen.sh && ./configure CC=clang CXX=clang++ LDFLAGS="-pthread -lpthread -lcurses -lz -ltinfo" --without-dragonegg
          make && make install && make check
      - name: Run CERE tests
        run: |
          XXX ADD EXPORTS HERE TO MATCH Build & install CERE (or push them before in the bashrc)
          make check
```
I am a bit surprised because the current serial version works well. So maybe it is something else... 
Can test by updating the test-build file?

**Comment by mihailpopov** [comment]
Adding the exports + locale-gen was the solution.

**Comment by pablooliveira** [comment]
@mihailpopov excellent !  Should we merge this now? Do you want us to review the PR?

**Comment by mihailpopov** [comment]
I think it is ready to be merged. 
We can later on further improve the code if we want.

**Pull request merged**
